### ISSUE TITLE
save emails to exel

### ISSUE THREAD

**Issue by glossyweb** [AyushSehrawat/email-scraper#2]
save emails to exel. can update code?

**Comment by AyushSehrawat** [comment]
@glossyweb You mean excel ?

**Comment by AyushSehrawat** [comment]
Sorry for being late , i didn't get any notifications of this issue

**Comment by glossyweb** [comment]
excel, csv, any file data

**Comment by AyushSehrawat** [comment]
@glossyweb Ohh kk

**Comment by AyushSehrawat** [comment]
@glossyweb Added csv  :-)
Closing issue
